name: Docker Build and Push to AWS Marketplace

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest'
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'Dockerfile'

jobs:
  build:
      if: github.actor == 'dependabot' || github.event_name == 'workflow_dispatch'
      runs-on:
          ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Login to ECR Registry
            uses: docker/login-action@v3
            env:
              AWS_REGION: us-east-1
            with:
              registry: 709825985650.dkr.ecr.us-east-1.amazonaws.com
              username: ${{ secrets.GHA_AWS_KEY }}
              password: ${{ secrets.GHA_AWS_KEY_ID }}

          - name: Get latest liquibase docker tag
            id: get_latest_tag
            run: |
              LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/library/liquibase/tags?page_size=1&page=4" | jq -r '.results[0].name')
              echo "LATEST_TAG=$LATEST_TAG"
              echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT

          - name: Build
            run: docker build -t 709825985650.dkr.ecr.us-east-1.amazonaws.com/liquibase/liquibase/liquibase-pro:${{ steps.get_latest_tag.outputs.LATEST_TAG || inputs.docker_tag }} .

          - name: Push to Docker Hub
            run: docker push 709825985650.dkr.ecr.us-east-1.amazonaws.com/liquibase/liquibase/liquibase-pro:${{ steps.get_latest_tag.outputs.LATEST_TAG || inputs.docker_tag }}