name: Update pom.xml with latest OSS Release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [secure-released-version]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  update-pom-secure-version:
    uses: liquibase/build-logic/.github/workflows/extension-release-prepare.yml@main
    secrets: inherit
