name: Update pom.xml with latest OSS Release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [oss-released-version]

jobs:
  update-pom-oss-version:
    uses: liquibase/build-logic/.github/workflows/extension-release-prepare.yml@v0.7.8
    secrets: inherit
    
